version: '3.8'

services:

  mysql-db:

    image: mysql:8.0

    container_name: mysql-db

    restart: unless-stopped

    environment:

      MYSQL_ROOT_PASSWORD: root123

      MYSQL_DATABASE: notesdb

    ports:

      - "3306:3306"

    volumes:

      - mysql_data:/var/lib/mysql
      - ./init.sql:/docker-entrypoint-initdb.d/init.sql

    networks:

      - notes-network



  flask-app:

    build: ./app

    container_name: flask-app

    restart: unless-stopped

    depends_on:

      - mysql-db

    ports:

      - "5000:5000"

    networks:

      - notes-network



networks:

  notes-network:



volumes:

  mysql_data: